// WORD LIST
let wordList= [
// A      
      "ABOUT", "ABOVE", "ABUSE", "ABYSS", "ACTOR", "ACUTE", "ADIEU", "ADMIT", "ADOPT", "ADORE", "ADULT", "AFFIX", "AFTER", "AGENT", "AGORA", "AGREE", "AHEAD", "ALARM", "ALBUM", "ALERT", "ALIEN", "ALIVE", "ALLEY", "ALONE", "ALONG", "ALPHA", "AMAZE", "AMONG", "AMPLE", "ANGEL", "ANGER", "ANGLE", "ANGLE", "ANGST", "ANKLE", "ANGRY", "APART", "APPLE", "APPLY", "ARENA", "ARGUE", "ARISE", "ARMOR", "AROMA", "ARROW", "ASIDE", "ASSET", "ATOMS", "AWAKE", "AVOID", "AWARD", "AWARE", "AZURE",
// B
      "BACON", "BADGE", "BADLY", "BAKED", "BAKER", "BALLS", "BANJO", "BANKS", "BARGE", "BARKS", "BASED", "BASES", "BASIC", "BASIN", "BATCH", "BATHE", "BEACH", "BEAMS", "BEANS", "BEARD", "BEARS", "BEAST", "BEATS", "BEGUN", "BEERS", "BEETS", "BEIGE", "BELCH", "BELLS", "BELLY", "BELOW", "BENCH", "BENDS", "BIBLE", "BIDES", "BIKES", "BINGE", "BINGO", "BILLS", "BINDS", "BIRDS", "BIRTH", "BISON", "BITES", "BLACK", "BLADE", "BLAME", "BLAND", "BLANK", "BLAST", "BLAZE", "BLEAK", "BLEED", "BLEND", "BLESS", "BLIND", "BLINK", "BLISS", "BLITZ", "BLOCK", "BLOOD", "BLOOM", "BLOWN", "BLOWS", "BLUES", "BLUFF", "BLUNT", "BLURB", "BLURT", "BLUSH", "BOARD", "BOAST", "BOATS", "BODES", "BOGUS", "BOILS", "BOLTS", "BONDS", "BONES", "BONUS", "BOOKS", "BOOMS", "BOONS", "BOOST", "BOOTH", "BOOTS", "BOOZE", "BORED", "BORES", "BORNE", "BOUND", "BOUTS", "BOWED", "BOWEL", "BOWER", "BOWLS", "BOXED", "BOXER", "BOXES", "BRACE", "BRAID", "BRAIN", "BRAKE", "BRAND", "BRASH", "BRAVE", "BRAVO", "BRAWL", "BRAWN", "BREAD", "BREAK", "BREED", "BREWS", "BRIAR", "BRIBE", "BRICK", "BRIDE", "BRIEF", "BRIER", "BRIMS", "BRINE", "BRING", "BRINK", "BRINY", "BROAD", "BROIL", "BROKE", "BROOD", "BROOK", "BROOM", "BROTH", "BROWN", "BRUSH", "BRUTE", "BUDDY", "BUDGE", "BUFFS", "BUGGY", "BUGLE", "BUILT", "BULBS", "BULGE", "BULLS", "BULLY", "BUMPS", "BUNCH", "BUNKS", "BUNNY", "BURNS", "BURNT", "BURST", "BUSES", "BUSHY", "BUTTS", "BUYER",
// C
      "CABLE", "CANDY", "CHAOS", "CHARM", "CHASE", "CHESS", "CHEAP", "CHILL", "CHIRP", "CHUNK", "CIDER", "CIVIC", "CIVIL", "CLASH", "CLASS", "CLEAN", "CLEAR", "CLIMB", "CLOUD", "CLOVE", "COAST", "CRANE", "CRASH", "CRATE", "CRAWL", "CRAZY", "CRISP", "CROWN", "CUBIC", "CURLY", "CURVE", "CYCLE", "CYBER", "CYNIC",
// D
      "DAILY", "DAISY", "DANCE", "DANDY", "DARTS", "DAUNT", "DEALT", "DEBIT", "DECAL", "DECOY", "DEFER", "DEITY", "DELAY", "DELTA", "DELVE", "DENSE", "DEVIL", "DICEY", "DIGIT", "DINER", "DINGO", "DIZZY", "DODGE", "DOCKS", "DOLLY", "DONOR", "DOORS", "DOUBT", "DOUGH", "DOUSE", "DRAFT", "DRAMA", "DRANK", "DRAPE", "DREAD", "DREAM", "DRIFT", "DRILL", "DRINK", "DRIVE", "DRONE", "DROVE", "DUCKS", "DUSTY", "DWELL", "DYING",
// E
      "EAGER", "EAGLE", "EERIE", "EIGHT", "EJECT", "ELBOW", "ELDER", "ELITE", "ELOPE", "ELUDE", "EMAIL", "EMBER", "EMPTY", "ENACT", "ENJOY", "ENTER", "ENTRY", "EPOCH", "EQUAL", "EQUIP", "ERASE", "ERROR", "EVENT", "EVERY", "EVOKE", "EXACT", "EXALT", "EXCEL", "EXERT", "EXILE", "EXIST", "EXITS", "EXTRA",
// F
      "FABLE", "FEAST", "FENCE", "FETCH", "FIGHT", "FIFTY", "FIZZY", "FLAIR", "FLARE", "FLAME", "FLASH", "FLESH", "FLINT", "FLOCK", "FLOOD", "FLUTE", "FORCE", "FOUND", "FRAIL", "FRANK", "FRESH", "FROST", "FROWN", "FRUIT", "FUNGI", "FUNNY", "FUNKY", "FUZZY",
// G
      "GAMER", "GAMES", "GAUGE", "GAUNT", "GAVEL", "GENRE", "GHOST", "GIDDY", "GLAND", "GLARE", "GLEAN", "GLIDE", "GLOBE", "GLOOM", "GLORY", "GLOVE", "GORGE", "GRACE",  "GRAND", "GRAPE", "GRASS", "GRAVE", "GRAZE", "GRASP", "GREET", "GRILL", "GRIND", "GROSS", "GUARD",
// H
      "HAPPY", "HASTE", "HASTY", "HATCH", "HEARD", "HEART", "HEIST", "HELLO", "HIKER", "HINGE", "HITCH", "HOBBY", "HONEY", "HORSE", "HOUND", "HOUSE", "HOVER", "HULKY", "HUMAN", "HUMID", "HURLS", "HURRY", "HUSKY", "HYENA", "HYDRA", "HYPER",
// I
      "ICILY", "ICING", "IDEAL", "IDEAS", "IGLOO", "IMAGE", "IMPLY", "INBOX", "INCUR", "INDEX", "INERT", "INFER", "INLAY", "INLET", "INNER", "INPUT", "INTRO", "IRATE", "IRONY", "ISSUE", "ITCHY", "IVORY",
// J
      "JAZZY", "JELLY", "JERKY", "JEWEL", "JOINT", "JOKER", "JOKES", "JOLLY", "JOUST", "JUDGE", "JUICE", "JUMPS", "JUMPY", "JUROR",
// K
      "KARMA", "KAYAK", "KIOSK", "KNACK", "KNAVE", "KNEAD", "KNEEL", "KNELT", "KNIFE", "KNOCK", "KOALA", "KUDOS",
// L
      "LASER", "LATCH", "LEAFY", "LEAST", "LEMON", "LEVEL", "LIGHT", "LIMBO", "LINGO", "LINKS", "LIVED", "LIVER", "LIVES", "LOCAL", "LODGE", "LOFTY", "LOVER", "LOWLY", "LUCID", "LUCKY", "LUNAR", "LUNGE", "LURCH", "LURID","LYRIC",
// M
      "MACHO", "MAGIC", "MAJOR", "MAKER", "MANGO", "MARCH", "MERIT", "METAL", "METER", "MIGHT", "MIMIC", "MINOR", "MIRTH", "MOLAR", "MONEY", "MOOSE", "MORAL", "MOTIF", "MOUNT", "MOUSE", "MOUTH", "MOVER", "MUNCH", "MURKY", "MUSIC", "MYTHS",
// N
      "NAIVE", "NASTY", "NERVE", "NEVER", "NICHE", "NIFTY", "NIGHT", "NINJA", "NINTH", "NOBLE", "NOISE", "NORTH", "NOTCH", "NUDGE", "NURSE", "NUTTY", "NYMPH",
// O
      "OASIS", "OCCUR", "OCEAN", "ODDLY", "OLDER", "OLIVE", "ONION", "ONSET", "OPTIC", "ORBIT", "ORDER", "ORGAN", "OTHER", "OUTDO", "OUTER", "OVERT", "OXIDE",
// P
      "PAINT", "PASTA", "PAVED", "PEARL", "PIANO", "PINKY", "PITCH", "PIVOT", "PIXEL", "PLACE", "PLANT", "PLAZA", "PLUCK", "PLUME", "PLUSH", "POINT", "POPPY", "POUCH", "POWER", "PRANK", "PRIDE", "PRIME", "PRINT", "PRISM", "PROUD", "PROWL", "PURGE", "PURSE", "PYGMY",
// Q
      "QUACK", "QUAIL", "QUARK", "QUASH", "QUEEN", "QUEUE", "QUEST", "QUICK", "QUIET", "QUILT", "QUIRK", "QUOTA", "QUOTE",
// R
      "RACER", "RALLY", "RANGE", "RATES", "RAVEN", "REACH", "REACT", "READY", "REBEL", "RECAP", "REIGN", "RELAY", "RHYME", "RIDER", "RIGHT", "RIGID", "RINSE", "RISKY", "RIVER", "ROCKY", "ROUGE", "ROUND", "ROUSE", "ROVER", "RUMBA", "RUMOR", "RUSTY",
// S
      "SCENT", "SCOOP", "SCOPE", "SCORE", "SCORN", "SHADE", "SHAPE", "SHEEP", "SHINY", "SHORE", "SHOUT", "SIGHT", "SKILL", "SLEEK", "SLEEP", "SLEET", "SLICK", "SLIDE", "SLOPE", "SNACK", "SNAKE", "SNEAK", "SNEER", "SOBER", "SOLID", "SPACE", "SPADE", "SPARK", "SPEAK", "SPEED", "SPEND", "SPICE", "SPIKE", "SPIKY", "SPILL", "SPILT", "SPINE", "SPITE", "SPLIT", "SPOOL", "SPORT", "SQUAD", "STARE", "STAND", "STEAL", "STEAM", "STING", "STONE", "STUCK", "SUGAR", "SUPER", "SWEEP", "SWING", "SWIRL", "SWORD", "SWUNG", "SYNTH",
// T
      "TABLE", "TALON", "TALES", "TANGO", "TENSE", "THANK", "THINK", "THIRD", "THORN", "THUMB", "TIGER", "TIMER", "TOAST", "TORCH", "TOUGH", "TOWEL", "TRACE", "TRACK", "TRAIL", "TREAD", "TREAT", "TREND", "TROPE","TRUST", "TWINE", "TWIST", "TWIRL", "TYPED", "TYPIC",
// U
      "ULTRA", "UNDER", "UNFIT", "UNIFY", "UNITE", "UNITY", "UNZIP", "UPEND", "UPPER", "UPSET", "URBAN", "URGED", "USAGE", "USHER", "USUAL", "USING", "UTTER",
// V
      "VAGUE", "VALUE", "VAPID", "VAPOR", "VAULT", "VAUNT", "VENOM", "VICES", "VIGOR", "VILLA", "VISTA", "VITAL", "VIVID", "VIXEN", "VOCAL", "VOTER", "VOWED", "VOWEL",
// W
      "WAGER", "WAGON", "WASTE", "WATER", "WAVER", "WEARY", "WHACK", "WHALE", "WHEAT", "WHINE", "WHIRL", "WHISK", "WIDEN", "WINCE", "WITTY", "WOOZY", "WOUND", "WOVEN", "WRIST", "WROTE", "WRUNG", 
// X
      "XENON",
// Y
      "YACHT", "YAWNS", "YEARN", "YEAST", "YIELD", "YIKES", "YODEL", "YOKEL", "YOUNG", "YOUTH", "YOWLS", "YUMMY",
// Z
      "ZAPPY", "ZEBRA", "ZESTS", "ZESTY", "ZILCH", "ZINGY", "ZINGS", "ZIPPY", "ZONAL", "ZONED", "ZONES"
]


